version: "3"
services:
  db:
    container_name: postgres-logbook-mbkm
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: logbook_km_unpas
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - service-logbook-km
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/redis-data:/data
    restart: always
    command:
      - redis-server --requirepass redis-12345
networks:
  service-logbook-km:
    driver: bridge